services:
  qdrant:
    container_name: meow-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # app:
  #   container_name: meow-app
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file: .env
  #   depends_on:
  #     - qdrant

volumes:
  qdrant_data:
