import logging
import random
import re

import httpx

from app.enums import ContentType, LiteralType
from app.schema.content import NewContent
from app.scrap.base import Scraper

logger = logging.getLogger(__name__)

_API_URL = "https://en.wikiquote.org/w/api.php"
_USER_AGENT = "meow-content-bot/1.0 (contact: ghkdgus28@gmail.com)"
_MAX_QUOTES_PER_FILM = 5

_SECTION_RE = re.compile(r"^==([^=\n].*?)==[ \t]*$", re.MULTILINE)
_BULLET_RE = re.compile(r"^[*:](?!\*|:)\s*(.+)$", re.MULTILINE)
_SPEAKER_RE = re.compile(r"^'''(?P<speaker>[^']+)'''\s*:\s*(?P<line>.+)$")
_REF_RE = re.compile(r"<ref[^>]*/?>.*?(</ref>|$)", re.DOTALL)
_SELF_CLOSING_REF_RE = re.compile(r"<ref[^>]*/>")
_LINK_RE = re.compile(r"\[\[(?:[^\]|]*\|)?([^\]]+)\]\]")
_LEADING_BRACKET_RE = re.compile(r"^\[[^\]]*\]\s*")
_SENTENCE_SPLIT_RE = re.compile(r"[.!?]+")

_POPULAR_MOVIES: tuple[str, ...] = (
    "The Godfather",
    "The Godfather Part II",
    "The Godfather Part III",
    "Casablanca",
    "Citizen Kane",
    "Pulp Fiction",
    "The Dark Knight",
    "The Dark Knight Rises",
    "Batman Begins",
    "Forrest Gump",
    "The Shawshank Redemption",
    "Fight Club",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "Star Wars (film)",
    "The Empire Strikes Back",
    "Return of the Jedi",
    "The Phantom Menace",
    "Attack of the Clones",
    "Revenge of the Sith",
    "The Force Awakens",
    "The Last Jedi",
    "The Rise of Skywalker",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: An Unexpected Journey",
    "Titanic (1997 film)",
    "Gladiator (2000 film)",
    "Inception",
    "Interstellar",
    "The Silence of the Lambs",
    "Goodfellas",
    "Casino (1995 film)",
    "Jaws (film)",
    "Back to the Future",
    "Back to the Future Part II",
    "Back to the Future Part III",
    "The Lion King",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Finding Nemo",
    "Up (2009 film)",
    "WALL-E",
    "Inside Out (2015 film)",
    "Coco (film)",
    "Frozen (2013 film)",
    "Aladdin (1992 film)",
    "Beauty and the Beast (1991 film)",
    "The Little Mermaid (1989 film)",
    "Mulan (1998 film)",
    "Shrek",
    "Shrek 2",
    "Monsters, Inc.",
    "The Incredibles",
    "Ratatouille (film)",
    "Zootopia",
    "How to Train Your Dragon (film)",
    "Jurassic Park (film)",
    "The Lost World: Jurassic Park",
    "E.T. the Extra-Terrestrial",
    "Raiders of the Lost Ark",
    "Indiana Jones and the Temple of Doom",
    "Indiana Jones and the Last Crusade",
    "Close Encounters of the Third Kind",
    "Saving Private Ryan",
    "Schindler's List",
    "The Sixth Sense",
    "Signs (2002 film)",
    "Unbreakable (film)",
    "Split (2016 film)",
    "Groundhog Day (film)",
    "Ghostbusters",
    "Home Alone",
    "Mrs. Doubtfire",
    "The Mask (film)",
    "Ace Ventura: Pet Detective",
    "Dumb and Dumber",
    "Liar Liar",
    "Men in Black (film)",
    "Independence Day (film)",
    "Armageddon (1998 film)",
    "The Rock (film)",
    "Con Air",
    "Speed (1994 film)",
    "Die Hard",
    "Die Hard 2",
    "Terminator 2: Judgment Day",
    "The Terminator",
    "RoboCop (1987 film)",
    "Predator (film)",
    "Alien (film)",
    "Aliens (film)",
    "Rocky",
    "Rocky II",
    "Rocky III",
    "Rocky IV",
    "Rambo: First Blood Part II",
    "First Blood",
    "Braveheart",
    "Troy (film)",
    "300 (film)",
    "The Patriot (2000 film)",
    "Gone with the Wind (film)",
    "Some Like It Hot",
    "Singin' in the Rain",
    "The Wizard of Oz (1939 film)",
    "Sunset Boulevard (film)",
    "12 Angry Men (1957 film)",
    "Vertigo (film)",
    "Rear Window",
    "Psycho (1960 film)",
    "North by Northwest",
    "To Kill a Mockingbird (film)",
    "One Flew Over the Cuckoo's Nest (film)",
    "Taxi Driver",
    "Apocalypse Now",
    "The Deer Hunter",
    "Full Metal Jacket",
    "Platoon (film)",
    "Good Morning, Vietnam",
    "American Beauty (1999 film)",
    "American History X",
    "Se7en",
    "American Psycho (film)",
    "Requiem for a Dream",
    "Donnie Darko",
    "Eternal Sunshine of the Spotless Mind",
    "Lost in Translation (film)",
    "The Grand Budapest Hotel",
    "The Royal Tenenbaums",
    "Little Miss Sunshine",
    "Juno (film)",
    "Superbad",
    "The 40-Year-Old Virgin",
    "Anchorman: The Legend of Ron Burgundy",
    "Step Brothers",
    "Zoolander",
    "There's Something About Mary",
    "American Pie (film)",
    "Animal House",
    "Caddyshack",
    "Ferris Bueller's Day Off",
    "The Breakfast Club",
    "Dirty Dancing",
    "Grease (film)",
    "Footloose (1984 film)",
    "Top Gun",
    "Top Gun: Maverick",
    "A Few Good Men",
    "JFK (film)",
    "Wall Street (1987 film)",
    "The Wolf of Wall Street",
    "The Social Network",
    "The Imitation Game",
    "A Beautiful Mind",
    "Catch Me If You Can",
    "The Aviator (film)",
    "Gangs of New York",
    "Shutter Island",
    "The Departed",
    "Django Unchained",
    "Inglourious Basterds",
    "Kill Bill: Volume 1",
    "Kill Bill: Volume 2",
    "Reservoir Dogs",
    "Once Upon a Time in Hollywood",
    "The Hateful Eight",
    "No Country for Old Men",
    "There Will Be Blood",
    "Fargo (film)",
    "The Big Lebowski",
    "Chinatown (1974 film)",
    "Network (1976 film)",
    "Amadeus (film)",
    "Dead Poets Society",
    "Good Will Hunting",
    "The Truman Show",
    "Cast Away",
    "Big (film)",
    "Field of Dreams",
    "Rain Man",
    "The Green Mile (film)",
    "The Prestige",
    "Memento (film)",
    "Whiplash (2014 film)",
    "La La Land",
    "Parasite (2019 film)",
    "Get Out (film)",
    "Us (2019 film)",
    "A Quiet Place (film)",
    "It (2017 film)",
    "The Shining (film)",
    "Halloween (1978 film)",
    "A Nightmare on Elm Street (1984 film)",
    "Scream (1996 film)",
    "Jurassic World",
    "Avengers: Endgame",
    "Iron Man (2008 film)",
    "Iron Man 2",
    "Iron Man 3",
    "The Incredible Hulk (film)",
    "Thor (film)",
    "Thor: The Dark World",
    "Thor: Ragnarok",
    "Thor: Love and Thunder",
    "Captain America: The First Avenger",
    "Captain America: The Winter Soldier",
    "Captain America: Civil War",
    "The Avengers (2012 film)",
    "Avengers: Age of Ultron",
    "Avengers: Infinity War",
    "Guardians of the Galaxy (film)",
    "Guardians of the Galaxy Vol. 2",
    "Guardians of the Galaxy Vol. 3",
    "Ant-Man (film)",
    "Ant-Man and the Wasp",
    "Doctor Strange (film)",
    "Doctor Strange in the Multiverse of Madness",
    "Spider-Man: Homecoming",
    "Spider-Man: Far From Home",
    "Spider-Man: No Way Home",
    "Black Panther (film)",
    "Black Panther: Wakanda Forever",
    "Captain Marvel (film)",
    "Shang-Chi and the Legend of the Ten Rings",
    "Eternals (film)",
    "Spider-Man (2002 film)",
    "Spider-Man 2",
    "Spider-Man 3",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "X-Men (film)",
    "X2 (film)",
    "X-Men: The Last Stand",
    "X-Men: First Class",
    "X-Men: Days of Future Past",
    "X-Men: Apocalypse",
    "Logan (film)",
    "Deadpool (film)",
    "Deadpool 2",
    "Fantastic Four (2005 film)",
    "Man of Steel (film)",
    "Batman v Superman: Dawn of Justice",
    "Suicide Squad (2016 film)",
    "Wonder Woman (2017 film)",
    "Justice League (film)",
    "Aquaman (film)",
    "Shazam! (film)",
    "Joker (2019 film)",
    "Birds of Prey (film)",
    "The Suicide Squad (film)",
    "The Batman",
    "Batman (1989 film)",
    "Batman Returns",
    "Batman Forever",
    "Batman & Robin (film)",
    "Batman: The Dark Knight Rises",
    "Superman (1978 film)",
    "Superman II",
    "Watchmen (film)",
    "V for Vendetta (film)",
    "Dr. No (film)",
    "From Russia with Love (film)",
    "Goldfinger (film)",
    "Thunderball (film)",
    "You Only Live Twice (film)",
    "On Her Majesty's Secret Service (film)",
    "Diamonds Are Forever (film)",
    "Live and Let Die (film)",
    "The Man with the Golden Gun (film)",
    "The Spy Who Loved Me (film)",
    "Moonraker (film)",
    "For Your Eyes Only (film)",
    "Octopussy",
    "A View to a Kill",
    "The Living Daylights",
    "Licence to Kill",
    "GoldenEye",
    "Tomorrow Never Dies",
    "The World Is Not Enough",
    "Die Another Day",
    "Casino Royale (2006 film)",
    "Quantum of Solace",
    "Skyfall",
    "Spectre (2015 film)",
    "No Time to Die",
    "Harry Potter and the Philosopher's Stone (film)",
    "Harry Potter and the Chamber of Secrets (film)",
    "Harry Potter and the Prisoner of Azkaban (film)",
    "Harry Potter and the Goblet of Fire (film)",
    "Harry Potter and the Order of the Phoenix (film)",
    "Harry Potter and the Half-Blood Prince (film)",
    "Harry Potter and the Deathly Hallows – Part 1",
    "Harry Potter and the Deathly Hallows – Part 2",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "The Fast and the Furious",
    "2 Fast 2 Furious",
    "The Fast and the Furious: Tokyo Drift",
    "Fast & Furious",
    "Fast Five",
    "Fast & Furious 6",
    "Furious 7",
    "The Fate of the Furious",
    "F9 (film)",
    "Fast X",
    "Mission: Impossible (film)",
    "Mission: Impossible II",
    "Mission: Impossible III",
    "Mission: Impossible – Ghost Protocol",
    "Mission: Impossible – Rogue Nation",
    "Mission: Impossible – Fallout",
    "Mission: Impossible – Dead Reckoning Part One",
    "Jurassic Park III",
    "Jurassic World: Fallen Kingdom",
    "Jurassic World Dominion",
    "Planet of the Apes (1968 film)",
    "Rise of the Planet of the Apes",
    "Dawn of the Planet of the Apes",
    "War for the Planet of the Apes",
    "Transformers (film)",
    "Transformers: Revenge of the Fallen",
    "Transformers: Dark of the Moon",
    "Transformers: Age of Extinction",
    "Transformers: The Last Knight",
    "Bumblebee (film)",
    "The Hunger Games (film)",
    "The Hunger Games: Catching Fire",
    "The Hunger Games: Mockingjay – Part 1",
    "The Hunger Games: Mockingjay – Part 2",
    "Twilight (2008 film)",
    "The Twilight Saga: New Moon",
    "The Twilight Saga: Eclipse",
    "The Twilight Saga: Breaking Dawn – Part 1",
    "The Twilight Saga: Breaking Dawn – Part 2",
    "Divergent (film)",
    "Insurgent (film)",
    "The Maze Runner (film)",
    "Shrek Forever After",
    "Puss in Boots (2011 film)",
    "Kung Fu Panda",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "Madagascar (film)",
    "Madagascar: Escape 2 Africa",
    "Ice Age (film)",
    "Ice Age: The Meltdown",
    "Ice Age: Dawn of the Dinosaurs",
    "How to Train Your Dragon 2",
    "How to Train Your Dragon: The Hidden World",
    "The Prince of Egypt",
    "Chicken Run",
    "Wallace & Gromit: The Curse of the Were-Rabbit",
    "Despicable Me",
    "Despicable Me 2",
    "Minions (film)",
    "The Croods",
    "Trolls (film)",
    "Home (2015 film)",
    "A Bug's Life",
    "Cars (film)",
    "Cars 2",
    "Cars 3",
    "Brave (2012 film)",
    "Monsters University",
    "Finding Dory",
    "Onward (film)",
    "Soul (film)",
    "Luca (film)",
    "Turning Red",
    "Lightyear (film)",
    "Elemental (film)",
    "Snow White and the Seven Dwarfs",
    "Pinocchio (1940 film)",
    "Fantasia (1940 film)",
    "Dumbo (1941 film)",
    "Bambi",
    "Cinderella (1950 film)",
    "Alice in Wonderland (1951 film)",
    "Peter Pan (1953 film)",
    "Lady and the Tramp",
    "Sleeping Beauty (1959 film)",
    "One Hundred and One Dalmatians",
    "The Jungle Book (1967 film)",
    "The Aristocats",
    "Robin Hood (1973 film)",
    "The Fox and the Hound",
    "The Great Mouse Detective",
    "Oliver & Company",
    "The Rescuers",
    "The Rescuers Down Under",
    "Pocahontas (film)",
    "The Hunchback of Notre Dame (1996 film)",
    "Hercules (1997 film)",
    "Tarzan (1999 film)",
    "Fantasia 2000",
    "The Emperor's New Groove",
    "Atlantis: The Lost Empire",
    "Lilo & Stitch",
    "Treasure Planet",
    "Brother Bear",
    "Home on the Range (film)",
    "Chicken Little (2005 film)",
    "Meet the Robinsons",
    "Bolt (film)",
    "The Princess and the Frog",
    "Tangled",
    "Wreck-It Ralph",
    "Ralph Breaks the Internet",
    "Big Hero 6 (film)",
    "Moana (2016 film)",
    "Frozen II",
    "Raya and the Last Dragon",
    "Encanto",
    "Wish (2023 film)",
    "Nausicaä of the Valley of the Wind (film)",
    "Castle in the Sky",
    "My Neighbor Totoro",
    "Grave of the Fireflies",
    "Kiki's Delivery Service",
    "Porco Rosso",
    "Princess Mononoke",
    "Spirited Away",
    "Howl's Moving Castle (film)",
    "Ponyo",
    "The Wind Rises",
    "The Tale of the Princess Kaguya",
    "Blade (film)",
    "Hellboy (2004 film)",
    "300: Rise of an Empire",
    "Kick-Ass (film)",
    "Chronicle (film)",
    "2001: A Space Odyssey (film)",
    "Blade Runner",
    "Blade Runner 2049",
    "A Clockwork Orange (film)",
    "Metropolis (1927 film)",
    "Solaris (1972 film)",
    "The Day the Earth Stood Still (1951 film)",
    "Forbidden Planet",
    "Invasion of the Body Snatchers (1956 film)",
    "The Time Machine (1960 film)",
    "Planet of the Apes (2001 film)",
    "Total Recall (1990 film)",
    "RoboCop (2014 film)",
    "Starship Troopers (film)",
    "Gattaca",
    "The Fifth Element",
    "Contact (1997 film)",
    "Minority Report (film)",
    "I, Robot (film)",
    "War of the Worlds (2005 film)",
    "District 9",
    "Moon (film)",
    "Ex Machina (film)",
    "Arrival (film)",
    "Edge of Tomorrow",
    "Looper (film)",
    "Source Code (film)",
    "Elysium (film)",
    "Oblivion (2013 film)",
    "Pacific Rim (film)",
    "The Martian (film)",
    "Ready Player One (film)",
    "Annihilation (film)",
    "Dune (2021 film)",
    "Dune: Part Two",
    "Tenet (film)",
    "A.I. Artificial Intelligence",
    "Children of Men",
    "Snowpiercer (film)",
    "The Exorcist",
    "Rosemary's Baby (film)",
    "Carrie (1976 film)",
    "The Omen",
    "Poltergeist (1982 film)",
    "The Fly (1986 film)",
    "An American Werewolf in London",
    "The Texas Chain Saw Massacre",
    "Friday the 13th (1980 film)",
    "A Nightmare on Elm Street 2: Freddy's Revenge",
    "Child's Play (1988 film)",
    "Hellraiser (film)",
    "The Evil Dead",
    "Evil Dead II",
    "Army of Darkness",
    "Night of the Living Dead",
    "Dawn of the Dead (1978 film)",
    "28 Days Later",
    "The Ring (2002 film)",
    "The Grudge (2004 film)",
    "Saw (2004 film)",
    "Saw II",
    "Hostel (film)",
    "Paranormal Activity (film)",
    "Insidious (film)",
    "The Conjuring",
    "The Conjuring 2",
    "Annabelle (film)",
    "Sinister (film)",
    "The Babadook",
    "It Follows",
    "Hereditary (film)",
    "Midsommar",
    "The Witch (2015 film)",
    "Bird Box (film)",
    "Don't Breathe",
    "Ready or Not (2019 film)",
    "Freaky (film)",
    "M3GAN",
    "Talk to Me (2022 film)",
    "Barbarian (film)",
    "All Quiet on the Western Front (1930 film)",
    "Paths of Glory",
    "The Bridge on the River Kwai",
    "Lawrence of Arabia (film)",
    "Patton (film)",
    "Dunkirk (2017 film)",
    "1917 (2019 film)",
    "Hacksaw Ridge",
    "We Were Soldiers",
    "Black Hawk Down (film)",
    "Zero Dark Thirty",
    "American Sniper",
    "Lone Survivor (film)",
    "The Hurt Locker",
    "Letters from Iwo Jima",
    "Flags of Our Fathers",
    "Pearl Harbor (film)",
    "Windtalkers",
    "The Thin Red Line (1998 film)",
    "Enemy at the Gates",
    "Downfall (film)",
    "The Pianist (film)",
    "Life Is Beautiful",
    "Fury (2014 film)",
    "War Horse (film)",
    "Come and See",
    "Das Boot",
    "West Side Story (1961 film)",
    "The Sound of Music (film)",
    "My Fair Lady (film)",
    "Mary Poppins (film)",
    "Oliver! (film)",
    "Fiddler on the Roof (film)",
    "Cabaret (1972 film)",
    "Chicago (2002 film)",
    "Moulin Rouge!",
    "The Greatest Showman",
    "Les Misérables (2012 film)",
    "Into the Woods (film)",
    "Mamma Mia! (film)",
    "Hairspray (2007 film)",
    "Rent (film)",
    "Sweeney Todd: The Demon Barber of Fleet Street (2007 film)",
    "The Rocky Horror Picture Show",
    "A Star Is Born (2018 film)",
    "Bohemian Rhapsody (film)",
    "Rocketman (film)",
    "Wonka (film)",
    "Rocky V",
    "Rocky Balboa",
    "Creed (film)",
    "Creed II",
    "Raging Bull",
    "The Karate Kid",
    "The Karate Kid Part II",
    "Hoosiers",
    "Rudy (film)",
    "Remember the Titans",
    "The Blind Side (film)",
    "Moneyball (film)",
    "Miracle (2004 film)",
    "Chariots of Fire",
    "Million Dollar Baby",
    "Any Given Sunday",
    "Jerry Maguire",
    "A League of Their Own",
    "Space Jam",
    "Cool Runnings",
    "We Are Marshall",
    "Invincible (2006 film)",
    "42 (film)",
    "Ford v Ferrari",
    "When Harry Met Sally...",
    "Pretty Woman",
    "Notting Hill (film)",
    "Four Weddings and a Funeral",
    "Bridget Jones's Diary",
    "Love Actually",
    "The Notebook (2004 film)",
    "10 Things I Hate About You",
    "Clueless (film)",
    "Mean Girls",
    "Legally Blonde",
    "She's the Man",
    "13 Going on 30",
    "Never Been Kissed",
    "She's All That",
    "The Princess Diaries",
    "You've Got Mail",
    "Sleepless in Seattle",
    "My Best Friend's Wedding",
    "How to Lose a Guy in 10 Days",
    "27 Dresses",
    "Crazy, Stupid, Love.",
    "Silver Linings Playbook",
    "500 Days of Summer",
    "The Fault in Our Stars",
    "Crazy Rich Asians",
    "To All the Boys I've Loved Before",
    "Easy A",
    "American Graffiti",
    "Dazed and Confused (film)",
    "Fast Times at Ridgemont High",
    "Napoleon Dynamite",
    "It Happened One Night",
    "Modern Times (film)",
    "City Lights",
    "The Grapes of Wrath (film)",
    "Mr. Smith Goes to Washington",
    "Stagecoach (1939 film)",
    "Rebecca (1940 film)",
    "The Maltese Falcon (1941 film)",
    "Double Indemnity",
    "Mildred Pierce (1945 film)",
    "It's a Wonderful Life",
    "The Best Years of Our Lives",
    "All About Eve",
    "A Streetcar Named Desire (1951 film)",
    "High Noon",
    "Roman Holiday",
    "On the Waterfront",
    "The Seven Year Itch",
    "Ben-Hur (1959 film)",
    "The Apartment",
    "The Manchurian Candidate (1962 film)",
    "Dr. Strangelove",
    "Who's Afraid of Virginia Woolf? (film)",
    "The Graduate",
    "Bonnie and Clyde (film)",
    "In the Heat of the Night (film)",
    "Midnight Cowboy",
    "Butch Cassidy and the Sundance Kid",
    "Easy Rider",
    "Love Story (1970 film)",
    "The French Connection (film)",
    "The Sting",
    "Annie Hall",
    "Saturday Night Fever",
    "Kramer vs. Kramer",
    "Airplane!",
    "On Golden Pond (1981 film)",
    "Gandhi (film)",
    "Tootsie",
    "Scarface (1983 film)",
    "Do the Right Thing",
    "Dances with Wolves",
    "Unforgiven",
    "The Usual Suspects",
    "The Bourne Identity",
    "The Bourne Supremacy",
    "The Bourne Ultimatum",
    "Crash (2004 film)",
    "Brokeback Mountain",
    "Slumdog Millionaire",
    "Avatar (2009 film)",
    "Up in the Air (2009 film)",
    "The King's Speech",
    "Black Swan (film)",
    "The Artist (film)",
    "Argo (2012 film)",
    "Gravity (film)",
    "12 Years a Slave",
    "Birdman (film)",
    "Spotlight (film)",
    "Moonlight (2016 film)",
    "The Shape of Water",
    "Green Book (film)",
    "Roma (2018 film)",
    "Nomadland",
    "Sound of Metal",
    "CODA (2021 film)",
    "Everything Everywhere All at Once",
    "The Banshees of Inisherin",
    "Oppenheimer (film)",
    "Barbie (film)",
    "Poor Things (film)",
    "Killers of the Flower Moon (film)",
    "Seven Samurai",
    "Rashomon",
    "Ikiru",
    "Yojimbo",
    "Ran (film)",
    "8½",
    "La Dolce Vita",
    "Bicycle Thieves",
    "The Bicycle Thief",
    "Cinema Paradiso",
    "Amélie",
    "Léon: The Professional",
    "La Haine",
    "The Intouchables",
    "City of God (2002 film)",
    "Pan's Labyrinth",
    "Y Tu Mamá También",
    "Crouching Tiger, Hidden Dragon",
    "Hero (2002 film)",
    "House of Flying Daggers",
    "In the Mood for Love",
    "Oldboy (2003 film)",
    "Train to Busan",
    "The Handmaiden",
    "Burning (2018 film)",
    "Memories of Murder",
    "The Wailing (film)",
    "Persona (1966 film)",
    "The Seventh Seal",
    "Wild Strawberries (film)",
    "Andrei Rublev",
    "Stalker (1979 film)",
    "The Lives of Others",
    "Run Lola Run",
    "Amores Perros",
    "Gone Girl (film)",
    "Prisoners (2013 film)",
    "Zodiac (film)",
    "The Girl with the Dragon Tattoo (2011 film)",
    "Nightcrawler (film)",
    "Wind River (film)",
    "Sicario (film)",
    "Sicario: Day of the Soldado",
    "Drive (2011 film)",
    "Baby Driver",
    "Collateral (film)",
    "Heat (1995 film)",
    "Training Day",
    "The Town (2010 film)",
    "Widows (film)",
    "Knives Out",
    "Glass Onion: A Knives Out Mystery",
    "Gone in 60 Seconds (2000 film)",
    "The Naked Gun",
    "Blazing Saddles",
    "Young Frankenstein",
    "Monty Python and the Holy Grail",
    "Life of Brian",
    "Office Space",
    "Zombieland",
    "Shaun of the Dead",
    "Hot Fuzz",
    "This Is the End",
    "Pineapple Express",
    "Knocked Up",
    "Bridesmaids (film)",
    "The Hangover",
    "The Hangover Part II",
    "Wedding Crashers",
    "Tropic Thunder",
    "Borat",
    "Jojo Rabbit",
    "Booksmart",
    "Game Night",
    "Free Guy",
    "Home Alone 2: Lost in New York",
    "Elf (film)",
    "A Christmas Story",
    "Miracle on 34th Street (1947 film)",
    "The Polar Express (film)",
    "How the Grinch Stole Christmas (2000 film)",
    "The Nightmare Before Christmas",
    "National Lampoon's Christmas Vacation",
    "Jumanji (1995 film)",
    "Jumanji: Welcome to the Jungle",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Charlie and the Chocolate Factory (film)",
    "Willy Wonka & the Chocolate Factory",
    "Matilda (1996 film)",
    "The Sandlot",
    "Free Willy",
    "Babe (film)",
    "Paddington (film)",
    "Paddington 2",
    "Cool Hand Luke",
    "The Great Escape",
    "Escape from Alcatraz",
    "Papillon (1973 film)",
    "American Gangster (film)",
    "Public Enemies (film)",
    "L.A. Confidential",
    "Mystic River (film)",
    "21 Grams",
    "Traffic (2000 film)",
    "Blow (film)",
    "Layer Cake (film)",
    "Snatch (film)",
    "Lock, Stock and Two Smoking Barrels",
    "The Long Good Friday",
    "Get Carter (1971 film)",
    "The Untouchables (film)",
    "Road to Perdition",
    "A History of Violence (film)",
    "Eastern Promises",
    "Wonder Woman 1984",
    "Godzilla vs. Kong",
    "Godzilla (2014 film)",
    "Kong: Skull Island",
    "Sonic the Hedgehog (film)",
    "A Quiet Place Part II",
    "Uncharted (film)",
    "Napoleon (2023 film)",
    "The Marvels",
    "Aquaman and the Lost Kingdom",
    "Midnight Express (film)",
    "Ordinary People",
    "Terms of Endearment",
    "Out of Africa (film)",
    "The Last Emperor",
    "Driving Miss Daisy",
    "Shakespeare in Love",
    "Tom Jones (1963 film)",
    "A Man for All Seasons (1966 film)",
    "Gigi (1958 film)",
    "An American in Paris (film)",
    "Around the World in 80 Days (1956 film)",
    "The Greatest Show on Earth",
    "Marty (film)",
    "Gentleman's Agreement",
    "From Here to Eternity",
    "Ocean's Eleven (2001 film)",
    "Ocean's Twelve",
    "Ocean's Thirteen",
    "The Italian Job (2003 film)",
    "Now You See Me",
    "Now You See Me 2",
    "Inside Man",
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3 – Parabellum",
    "John Wick: Chapter 4",
    "Mad Max 2",
    "Mad Max Beyond Thunderdome",
    "Mad Max (film)",
    "Misery (film)",
    "Stand by Me (film)",
    "IT Chapter Two",
    "Doctor Sleep (film)",
    "The Dead Zone (film)",
    "Christine (1983 film)",
    "Pet Sematary (1989 film)",
    "Gerald's Game (film)",
    "The Mist (film)",
    "1408 (film)",
    "Beetlejuice",
    "Edward Scissorhands",
    "Sleepy Hollow (1999 film)",
    "Big Fish",
    "Corpse Bride",
    "Alice in Wonderland (2010 film)",
    "Dark Shadows (film)",
    "American Pie 2",
    "Grease 2",
    "Sixteen Candles",
    "Can't Hardly Wait",
    "Not Another Teen Movie",
    "The Perks of Being a Wallflower (film)",
    "Love, Simon",
    "To All the Boys: P.S. I Still Love You",
    "Predator 2",
    "True Lies",
    "Commando (1985 film)",
    "Lethal Weapon",
    "Lethal Weapon 2",
    "Lethal Weapon 3",
    "Beverly Hills Cop",
    "Beverly Hills Cop II",
    "48 Hrs.",
    "Point Break (1991 film)",
    "Point Break (2015 film)",
    "The Fugitive (1993 film)",
    "Air Force One (film)",
    "Executive Decision",
    "Under Siege",
    "Face/Off",
    "Twister (1996 film)",
    "Volcano (1997 film)",
    "Dante's Peak",
    "Deep Impact",
    "The Day After Tomorrow",
    "2012 (film)",
    "San Andreas (film)",
    "The Poseidon Adventure",
    "The Towering Inferno",
    "Earthquake (1974 film)",
    "The Good, the Bad and the Ugly",
    "A Fistful of Dollars",
    "For a Few Dollars More",
    "Once Upon a Time in the West",
    "True Grit (1969 film)",
    "True Grit (2010 film)",
    "Tombstone (film)",
    "The Magnificent Seven (1960 film)",
    "The Wild Bunch",
    "High Plains Drifter",
    "Django (1966 film)",
    "King Kong (1933 film)",
    "King Kong (2005 film)",
    "Godzilla (1954 film)",
    "The Blob",
    "Them! (film)",
    "Creature from the Black Lagoon",
    "The Invisible Man (1933 film)",
    "Frankenstein (1931 film)",
    "Dracula (1931 English-language film)",
    "The Wolf Man (1941 film)",
    "Your Name (film)",
    "Weathering with You",
    "A Silent Voice (film)",
    "Perfect Blue",
    "Akira (1988 film)",
    "Ghost in the Shell (1995 film)",
    "Nope (film)",
    "X (2022 film)",
    "Pearl (film)",
    "Smile (2022 film)",
    "Terrifier 2",
    "Longlegs",
    "Cocaine Bear",
    "Venom (2018 film)",
    "Venom: Let There Be Carnage",
    "Spider-Man: Into the Spider-Verse",
    "Spider-Man: Across the Spider-Verse",
    "Glory (1989 film)",
    "Gettysburg (1993 film)",
    "Life of Pi (film)",
    "The Farewell (2019 film)",
    "Minari",
    "Dreamgirls (film)",
    "Hairspray (1988 film)",
    "The Help (film)",
    "Hidden Figures",
    "Fences (film)",
    "Anatomy of a Fall",
    "The Zone of Interest",
    "Past Lives (film)",
    "American Fiction (film)",
    "Maestro (2023 film)",
    "Amistad (film)",
    "Philadelphia (film)",
    "The Insider (film)",
    "Erin Brockovich (film)",
    "A Civil Action (film)",
    "Coming to America",
    "Trading Places",
    "Ghostbusters II",
    "Big Trouble in Little China",
    "The Princess Bride",
    "Deadpool & Wolverine",
    "The Incredibles 2",
    "Demon Slayer: Mugen Train",
    "Decision to Leave",
    "The Holiday (film)",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Extraction (2020 film)",
    "The Old Guard (film)",
    "6 Underground",
    "Uncut Gems",
    "The Lighthouse (2019 film)",
    "The Menu (2022 film)",
    "Triangle of Sadness",
    "Don't Look Up",
    "The Trial of the Chicago 7",
    "The Report (film)",
    "Vice (2018 film)",
    "BlacKkKlansman",
    "Da 5 Bloods",
    "If Beale Street Could Talk",
    "Little Women (2019 film)",
    "Lady Bird (film)",
    "Call Me by Your Name (film)",
    "Manchester by the Sea (film)",
    "Room (2015 film)",
    "The Revenant (2015 film)",
    "Mad Max: Fury Road",
    "Bridge of Spies",
    "Sully (film)",
    "Captain Phillips (film)",
    "Rush (2013 film)",
    "Foxcatcher",
    "The Theory of Everything (film)",
    "The Danish Girl (film)",
    "A Star Is Born (1976 film)",
    "Funny Girl (film)",
    "Yentl (film)",
    "Victor/Victoria",
    "Evita (film)",
    "Nine (2009 film)",
    "Wicked (2024 film)",
)

_DIALOGUE_HEADING = "dialogue"
# Known catch-all headings that appear before "Dialogue" but aren't a single
# character's curated quotes. Most such sections are already caught structurally
# (see _extract_quote_candidates), but add exceptions here as they're found.
_EXCLUDED_HEADINGS = {"others"}


def _strip_refs_and_links(text: str) -> str:
    text = _REF_RE.sub("", text)
    text = _SELF_CLOSING_REF_RE.sub("", text)
    text = _LINK_RE.sub(r"\1", text)
    return text


def _strip_emphasis(text: str) -> str:
    text = text.replace("'''", "").replace("''", "")
    text = _LEADING_BRACKET_RE.sub("", text)
    return text.strip()


def _parse_speaker_bullet(raw: str) -> tuple[str, str] | None:
    # Speaker detection must run before bold-marker stripping, since it matches on
    # the literal '''Speaker''' markers that _strip_emphasis would otherwise remove.
    structural = _strip_refs_and_links(raw)
    match = _SPEAKER_RE.match(structural)
    if not match:
        return None
    return _strip_emphasis(match.group("speaker")), _strip_emphasis(match.group("line"))


def _sentence_count(text: str) -> int:
    return len([s for s in _SENTENCE_SPLIT_RE.split(text) if s.strip()])


def _sections(wikitext: str) -> list[tuple[str, str]]:
    matches = list(_SECTION_RE.finditer(wikitext))
    result = []
    for i, match in enumerate(matches):
        heading = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(wikitext)
        result.append((heading, wikitext[start:end]))
    return result


def _dialogue_index(sections: list[tuple[str, str]]) -> int | None:
    for i, (heading, _) in enumerate(sections):
        if heading.strip().lower() == _DIALOGUE_HEADING:
            return i
    return None


def _extract_quote_candidates(film_wikitext: str) -> list[tuple[str, str]]:
    sections = _sections(film_wikitext)
    dialogue_index = _dialogue_index(sections)
    if dialogue_index is None:
        return []

    candidates: list[tuple[str, str]] = []
    for heading, body in sections[:dialogue_index]:
        if heading.strip().lower() in _EXCLUDED_HEADINGS:
            continue

        raw_bullets = _BULLET_RE.findall(body)
        if any(_parse_speaker_bullet(raw) is not None for raw in raw_bullets):
            # Section mixes multiple speakers inline (e.g. a catch-all "Others"
            # or "Quotes from <Source> Literature" section) rather than being a
            # single character's curated quotes — skip it entirely rather than
            # misattribute every line to the section heading.
            continue

        for raw in raw_bullets:
            line = _strip_emphasis(_strip_refs_and_links(raw))
            if not (1 <= _sentence_count(line) <= 2) or "http" in line:
                continue
            candidates.append((heading, line))
    return candidates


def _strip_disambiguation(title: str) -> str:
    return re.sub(r"\s*\([^()]*\)\s*$", "", title)


class WikiquoteMovieScraper(Scraper):
    async def _fetch_wikitext(
        self, client: httpx.AsyncClient, title: str
    ) -> str | None:
        response = await client.get(
            _API_URL,
            params={
                "action": "parse",
                "page": title,
                "prop": "wikitext",
                "format": "json",
                "formatversion": 2,
                "redirects": 1,
            },
        )
        response.raise_for_status()
        data = response.json()
        if "error" in data:
            logger.warning(
                "Wikiquote page %r missing or errored: %s", title, data["error"]
            )
            return None
        return data["parse"]["wikitext"]

    async def scrape(self) -> list[NewContent]:
        async with httpx.AsyncClient(
            timeout=30, headers={"User-Agent": _USER_AGENT}
        ) as client:
            film_title = random.choice(_POPULAR_MOVIES)
            logger.info("Selected movie for scraping: %r", film_title)
            film_wikitext = await self._fetch_wikitext(client, film_title)
            if film_wikitext is None:
                return []

            candidates = _extract_quote_candidates(film_wikitext)
            if not candidates:
                logger.warning("No usable quotes parsed for film %r", film_title)
                return []

            chosen = random.sample(
                candidates, min(len(candidates), _MAX_QUOTES_PER_FILM)
            )
            display_title = _strip_disambiguation(film_title)
            return [
                NewContent(
                    type=ContentType.LiteralQuote,
                    content=line,
                    author=author,
                    title=display_title,
                    literal_type=LiteralType.MOVIE,
                )
                for author, line in chosen
            ]


wikiquote_movie_scraper = WikiquoteMovieScraper()
